RegisterNetEvent('rw:polisine')
AddEventHandler('rw:polisine', function()
TriggerServerEvent('duty:onoff')
--TriggerEvent("mystoria-polisi:updateBlip")
TriggerEvent('rw:leng')
end)

RegisterNetEvent('rw:mechanic')
AddEventHandler('rw:mechanic', function()
--TriggerEvent("mystoria-polisi:updateBlip")
TriggerServerEvent('duty:onoff')
TriggerEvent('rw:leng')
end)

RegisterNetEvent('rw:ambulance')
AddEventHandler('rw:ambulance', function()
TriggerServerEvent('duty:onoff')
TriggerEvent('rw:leng')
end)

RegisterNetEvent('rw:pedagang')
AddEventHandler('rw:pedagang', function()
TriggerServerEvent('duty:onoff')
TriggerEvent('rw:leng')
end)